### ISSUE TITLE
TSX Support?

### ISSUE THREAD

**Issue by TimMensch** [danhuang1202/amp-react-components#2]
Unless I'm misunderstanding something, the components don't work in TSX in strict mode:

```tsx
 <AmpSidebar id="sidebar-left" layout="nodisplay" side="left">
...
</AmpSideBar>
```

Code that looks like the above fails with:

```
Type '{ children: Element[]; id: string; layout: string; side: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Props'.ts(2322)
```

And code that looks exactly like your sample:

```tsx
function component() {
    return (
        <AmpImg
            className="amp-close-image"
            src="image/close.png"
            width="1"
            height="1"
            layout="responsive"
        />
    );
}
```

...fails with 

```
Type '{ className: string; src: string; width: string; height: string; layout: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'src' does not exist on type 'IntrinsicAttributes & Props'.ts(2322)
```

It wants the props to have all of the members, and to _not_ have an expected `props` member.

I wouldn't ask except it looks like you're _using_ TypeScript, so I'm curious as to why you don't have full TSX support. I'm on TypeScript 3.7.5 and React 16.13.0.

**Comment by TimMensch** [comment]
Never mind. Found react-amphtml which works correctly with TypeScript/ 3.7.5/tsx.
